spring.application.name=kafka-stream-spring-cloud
server.port=8081
spring.cloud.stream.bindings.pageEventConsumer-in-0.destination=T2
spring.cloud.stream.bindings.pageEventSupplier-out-0.destination=T3

spring.cloud.function.definition=pageEventConsumer; pageEventSupplier
#reglage du supplier pour un interval particulier
spring.cloud.stream.bindings.pageEventSupplier-out-0.producer..poller.fixed-delay=200