spring.application.name=kafka-stream-spring-cloud
server.port=8081
spring.cloud.stream.bindings.pageEventConsumer-in-0.destination=T2
spring.cloud.stream.bindings.pageEventSupplier-out-0.destination=T3

spring.cloud.function.definition=pageEventConsumer; pageEventSupplier; kstreamFunction;
#reglage du supplier pour un interval particulier
spring.cloud.stream.bindings.pageEventSupplier-out-0.producer..poller.fixed-delay=1000

spring.cloud.stream.bindings.kstreamFunction-in-0.destination=T3
spring.cloud.stream.bindings.kstreamFunction-out-0.destination=T4
#reglage du processor pour un interval particulier
spring.cloud.stream.kafka.streams.binder.configuration.commit.interval.ms=1000